FROM python:3.9-slim

ARG ES_PY_VERSION="elasticsearch>=7,<8"
ARG OS_PY_VERSION="opensearch-py>=2,<3"

RUN pip install --no-cache-dir \
    "pytest" \
    "htcondor" \
    "${ES_PY_VERSION}" \
    "${OS_PY_VERSION}"

RUN useradd -m submituser

WORKDIR /tests
USER submituser
CMD ["pytest", "-v", "-s"]
